services:
  app:
    build: .
    ports:
      - "8080:8080"
#    volumes:
#      - ./secrets/guardian.api-key:/run/secrets/guardian.api-key:ro
#      - ./secrets/newsapi.api-key:/run/secrets/newsapi.api-key:ro
#    environment:
#      SPRING_CONFIG_IMPORT: optional:configtree:/run/secrets/

    environment:
      - GUARDIAN_API_KEY=${GUARDIAN_API_KEY}
      - LINE_CHANNEL_TOKEN=${LINE_CHANNEL_TOKEN}
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}