services:
  app:
    build: .
    ports:
      - "8080:8080"
    secrets:
      - source: guardian_api_key
        target: guardian.api_key
      - source: news_api_key
        target: news.api-key       #mount to /run/secrets/newsapi.api-key

secrets:
  guardian_api_key:
    # take the value from an env var on the host (e.g., .env file)
    environment: GUARDIAN_API_KEY
  news_api_key:
    environment: NEWS_API_KEY
