spring:
  application:
    name: digest

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  config:
    import: "optional:configtree:/run/secrets/"

# external API settings
source:
  hn:
    base-url: https://hacker-news.firebaseio.com/v0

  guardian:
    base-url: https://content.guardianapis.com

  newsapi: {}

# (optional) Feign timeouts/logging
feign:
  client:
    config:
      default:
        connectTimeout: 4000
        readTimeout: 5000
        loggerLevel: BASIC
